version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: wordy-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wordy
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql # optional seed

volumes:
  db_data: